### ISSUE TITLE
How do you indicate CUDA_VERSION=12.4.1?

### ISSUE THREAD

**Issue by f0nzie** [b-data/data-science-devcontainers#10]
I am trying to build the CUDA r-base containers but I am receiving errors during the build: " requirement error: unsatisfied condition: cuda>=12.5". 

Host OS: Linux Fedora Silverblue 40
Host CUDA: 12.4.1
GPU: NVIDIA RTX 3080
Build: Local
IDE: VS Code
Method: "Reopen in Container"
Extension: DevContainer

![image](https://github.com/b-data/data-science-devcontainers/assets/29108853/49a68a40-7ec0-414e-ba44-1e478e3b3509)

It seems that something changed during the past days because last week I was able to build cuda-r-base, and yesterday and today, the containers do not build anymore.

**Last week**, I made a build status table to check which images built fine.

![image](https://github.com/b-data/data-science-devcontainers/assets/29108853/5a8df227-45f2-4642-837c-6fdc0245a5a0)

But as of today, none of them run.

Any clues?

**Comment by benz0li** [comment]
> Any clues?

My fault.

I forgot to update the `README`: CUDA-based images are now derived from [`nvidia/cuda:12.5.0-runtime-ubuntu22.04`](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=12.5.0-runtime-ubuntu22.04).

Updated right now: https://github.com/b-data/data-science-devcontainers/commit/bc3af9f8821c736fc1d3268772fdfb5a227b5ab0

**Comment by benz0li** [comment]
ℹ️ The host running the GPU accelerated Dev Containers only requires the NVIDIA driver, the CUDA toolkit does not have to be installed.

**Comment by benz0li** [comment]
In order to run the current Data Science Dev Containers you require a NVIDIA Linux driver version ≥ 555.42.02.

https://www.nvidia.com/download/driverResults.aspx/224751/en-us/

**Comment by benz0li** [comment]
The **latest** versions of the CUDA Julia/Python/R Data Science Dev Containers are [currently] based on the **latest** version of [`nvidia/cuda`](https://hub.docker.com/r/nvidia/cuda).

Any other version than **latest** is *frozen* (see [Security](../blob/main/SECURITY.md)), i.e. does not get updated [any more].  
ℹ️ E.g. the **last** Dev Containers that are based on [nvidia/cuda:11.8.0-cudnn8-devel-ubuntu22.04](https://hub.docker.com/r/nvidia/cuda/tags?page=1&name=11.8.0-cudnn8-devel-ubuntu22.04) are

* R 4.3.3
* Python 3.11[.9]
* Julia 1.10.1

👉 Pass `R_VERSION=4.3.3`, `PYTHON_VERSION=3.11[.9]` or `JULIA_VERSION=1.10.1` as `build.args` to create the Data Science Dev Container to get an image that runs with any NVIDIA Linux driver version ≥ 520.61.05.

**Comment by f0nzie** [comment]
Oh, I see. I have the Driver Version: 550.78 for CUDA Version: 12.4.
> "Pass R_VERSION=4.3.3, PYTHON_VERSION=3.11[.9] or JULIA_VERSION=1.10.1 as build.args to create the Data Science Dev Container to get an image that runs with any NVIDIA Linux driver version ≥ 520.61.05."

Do you mean, I could be able to build an image with a lesser CUDA version (12.4) if I choose R-4.3.3 instead of latest?

**Comment by benz0li** [comment]
> Do you mean, I could be able to build an image with a lesser CUDA version (12.4) if I choose R-4.3.3 instead of latest?

Yes.

**Comment by benz0li** [comment]
See also

* Julia: [CUDA Version Matrix](https://github.com/b-data/jupyterlab-julia-docker-stack/blob/main/CUDA_VERSION_MATRIX.md)
* Python: [CUDA Version Matrix](https://github.com/b-data/jupyterlab-python-docker-stack/blob/main/CUDA_VERSION_MATRIX.md)
* R: [CUDA Version Matrix](https://github.com/b-data/jupyterlab-r-docker-stack/blob/main/CUDA_VERSION_MATRIX.md)

**Comment by benz0li** [comment]
Another possibility is to use a *Long Term Support Branch* (LTSB) driver:

* [470](https://www.nvidia.com/download/driverResults.aspx/226760/en-us/): CUDA 11.0+
  * Capable of running all CUDA-based Data Science Dev Containers
* [535](https://www.nvidia.com/download/driverResults.aspx/226764/en-us/): CUDA 12.2+
  * Capable of running only 'CUDA 12'-based Data Science Dev Containers 

Cross references:

* https://docs.nvidia.com/deploy/cuda-compatibility/index.html#id3 [^1]
* https://gitlab.com/nvidia/container-images/cuda/-/blob/master/doc/container_tags.pdf

[^1]: The Data Science Dev Containers, i.e. the [nvidia/cuda](https://hub.docker.com/r/nvidia/cuda) images, already have the right *CUDA forward compat package* installed.

**Comment by benz0li** [comment]
I have updated the R [CUDA Version Matrix](https://github.com/b-data/jupyterlab-r-docker-stack/blob/main/CUDA_VERSION_MATRIX.md) accordingly.

@f0nzie Please close this issue if your problem is resolved.

**Comment by f0nzie** [comment]
> Yes (`R_VERSION=4.3.3` instead of `R_VERSION=4.4.0`).

Awesome!
Tried downgrading to one version previous to `latest`  last night and all CUDA images work!

![image](https://github.com/b-data/data-science-devcontainers/assets/29108853/a5d28742-4a95-4d7e-b975-d2a88a833080)

Thank you so much!

**Comment by f0nzie** [comment]
> * [470](https://www.nvidia.com/download/driverResults.aspx/226760/en-us/): CUDA 11.0+
> * [535](https://www.nvidia.com/download/driverResults.aspx/226764/en-us/): CUDA 12.2+

That is a good alternative. I have the 550.78 driver in myu machines. That is maybe the reason the image build failed.

**Comment by benz0li** [comment]
@f0nzie The **last** versions running CUDA 11.8.0 are

* R 4.3.3
* Python 3.12.1
  * Python 3.11.9 and future 3.11 releases
* Julia 1.10.1

**Comment by benz0li** [comment]
> > * [470](https://www.nvidia.com/download/driverResults.aspx/226760/en-us/): CUDA 11.0+
> > * [535](https://www.nvidia.com/download/driverResults.aspx/226764/en-us/): CUDA 12.2+
> 
> That is a good alternative. I have the 550.78 driver in my machine. That is maybe the reason the image build failed.

If you install[^1] Linux driver version [535](https://www.nvidia.com/download/driverResults.aspx/226764/en-us/), you can build and run all available Data Science Dev Containers for the next two years; this driver does not reach EOL until June 2026.

[^1]: and update from time to time

**Comment by benz0li** [comment]
ℹ️ Using Linux driver versions [470](https://www.nvidia.com/download/driverResults.aspx/226760/en-us/)/[535](https://www.nvidia.com/download/driverResults.aspx/226764/en-us/) with 'CUDA 12'-based Data Science Dev Containers only works with [NVIDIA Data Center GPUs](https://resources.nvidia.com/l/en-us-gpu) or [select NGC-Ready NVIDIA RTX boards](https://docs.nvidia.com/certification-programs/ngc-ready-systems/index.html).

**Comment by benz0li** [comment]
The new *Long Term Support Branch* (LTSB) driver version is 580 now:

* [580](https://www.nvidia.com/en-us/drivers/details/267258/): CUDA 13.0+
  * 'CUDA 13'-based Data Science dev containers: Supported via minor version compatibility
  * 'CUDA 12'-based Data Science dev containers: Supported via backward compatibility
  * 'CUDA 11'-based Data Science dev containers: Supported via backward compatibility

Official NVIDIA documentation regarding driver versions and CUDA compatibility:

- [NVIDIA Data Center Drivers: Supported Drivers and CUDA Toolkit Versions](https://docs.nvidia.com/deploy/cuda-compatibility/forward-compatibility.html)
  - [CUDA Compatibility: Minor Version Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/minor-version-compatibility.html)
  - [CUDA Compatibility: Forward Compatibility](https://docs.nvidia.com/deploy/cuda-compatibility/forward-compatibility.html)
