### ISSUE TITLE
Basic usage questions

### ISSUE THREAD

**Issue by jpvelez** [b-data/data-science-devcontainers#14]
Hello! This project looks super cool, and I'm trying to work out how to use it.

My ultimate goal is to use `glcr.b-data.ch/jupyterlab/r/geospatial` as a development environment in vscode (the desktop version, not the browser version).

A few questions!

- Should I just use `glcr.b-data.ch/jupyterlab/r/geospatial`?
- What does this devcontainers repo add, and how do you use it? I'm not sure what is meant by "The default dev container is meant to work on this repository."? I guess I'm not totally sure how devcontainers are supposed to work... I've never used `Dev Container: Reopen on Container`, only `Dev Container: Attach to Running Container` after starting our current development docker image with Docker compose.
- Your code-server extensions look great; is there a way to get the desktop app to use these extensions once I'm connected to the repo?
- The README says: "Data in the following locations is persisted: The user's home directory, /home/vscode; The dev container's workspace (/workspaces)." Is it possible to override the directory where files are mounted to something other than home/vscode? (Will that screw something up?) Also, why would workspaces be persisted, and where?

**Comment by jpvelez** [comment]
Okay, I did a lot of reading about devcontainers and I think: 1. devcontainers are awesome and 2. I answered the first 3/4 questions above.

So I still have the last question, about persisting the workspace.

And new question, if I use [this devcontainer](https://github.com/b-data/data-science-devcontainers/blob/main/.devcontainer/r-geospatial/devcontainer.json) what's the intended mechanism for adding my own R and Python packages? Should I make my own Dockerfile based on yours and point the r-geosptial devcontainer at that one instead?

**Comment by benz0li** [comment]
> Is it possible to override the directory where files are mounted to something other than `/home/vscode`? (Will that screw something up?)

The idea is that you store your work within the (default) user's *home directory* (`/home/vscode`, e.g. folder `~/projects`) – as you would with a regular Linux distribution.  
ℹ️ Persisting the *home directory* also ensures that *dot files/folders* (e.g. settings) are persisted.

By default, mount type `volume` is used, so Dev Containers behave the same as Codespaces.  
ℹ️ See also [[Data Science dev containers] Do they work with bind mounts?](https://github.com/orgs/b-data/discussions/2)

> Also, why would workspaces be persisted, and where?

`/workspaces` is persisted by default. Where?

* Dev Container: The (Git) Repository is bind mounted to `/workspaces/$RepositoryName`
  * Persisted on your local file system
* Codespaces: The (Git) Repository is cloned to `/workspaces/$RepositoryName`
  * Persisted on a *loop device*

**Comment by benz0li** [comment]
> And new question, if I use [this devcontainer](https://github.com/b-data/data-science-devcontainers/blob/main/.devcontainer/r-geospatial/devcontainer.json) what's the intended mechanism for adding my own R and Python packages?

The idea is that you install additional packages at runtime.

1. R: `install.packages("<package>")`
    * Installed at `${HOME}/R/$(uname -m)-pc-linux-gnu-library/${R_VERSION%.*}`
1. Python: `pip install <package>`
    * Installed at `${HOME}/.local/lib/python${PYTHON_VERSION%.*}/site-packages`

ℹ️ Because the *home directory* is persisted, this ensures that installed packages are also persisted.

> Should I make my own Dockerfile based on yours and point the r-geosptial devcontainer at that one instead?

That is entirely up to you.

**Comment by benz0li** [comment]
If you have a Python project with a `requirements.txt` file:

1. `cd ~/projects`
2. `git clone <repository>`
3. `cd ~/projects/<repository>`
4. `pip install -r requirements.txt`

Related:

* https://github.com/b-data/data-science-devcontainers/issues/15

**Comment by jpvelez** [comment]
Interesting approach, wouldn't have considered it. We also install packages into the container so everyone has the same versions and results are reproducible, but this would certainly be more lightweight.

Thanks for your help!

**Comment by benz0li** [comment]
> Interesting approach, wouldn't have considered it.

Usually, a Dev Container is tailored for a single repository [and is part of it].

**Comment by benz0li** [comment]
I wanted to create Dev Containers that could be used for multiple [Data Science] repositories. Similar in functionality to the [Jupyter](https://github.com/b-data/jupyterlab-mojo-docker-stack)[Lab](https://github.com/b-data/jupyterlab-julia-docker-stack) [docker](https://github.com/b-data/jupyterlab-python-docker-stack) [stacks](https://github.com/b-data/jupyterlab-r-docker-stack), except that

* GPU accelerated dev containers are based on the [NVIDIA CUDA](https://hub.docker.com/r/nvidia/cuda) **runtime** flavoured image.
  * The JupyterLab docker stacks are based on the NVIDIA CUDA **devel** flavoured image.
* Dev containers' Oh My Zsh uses the **devcontainers theme + default font**.
  * The JupyterLab docker stacks' Oh My Zsh uses **Powerlevel10k theme + MesloLGS NF font**.
