### ISSUE TITLE
How can I run a container with both, Julia and R installed?

### ISSUE THREAD

**Issue by iagobaapellaniz** [b-data/data-science-devcontainers#17]
Sorry for the naive question, but I am not able to get both installed on a single container.
Thanks in advance

**Comment by benz0li** [comment]
> Sorry for the naive question, but I am not able to get both installed on a single container.

@iagobaapellaniz This repository does not offer a dev container containing both Julia and R.

**Comment by benz0li** [comment]
The dev containers currently offer either Python 3.13.0 or

1. Julia 1.11.2 + Python 3.12.7
2. MAX/Mojo 24.5.0 + Python 3.12.7
3. R 4.4.2 + Python 3.12.7

I have no intention to create a dev container offering Julia 1.11.2 + R 4.4.2 + Python 3.12.7.
